[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  included_files = ["node_modules/@sparticuz/chromium/bin/**"]

[build.environment]
  NODE_VERSION = "20"
  NETLIFY = "true"
  NODE_ENV = "production"


