[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "netlify-plugin-chromium"

[functions]
  node_bundler = "esbuild"

# Environment variables for Netlify
[build.environment]
  NODE_VERSION = "20"
  NETLIFY = "true"
  NODE_ENV = "production"


