[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  included_files = ["node_modules/@sparticuz/chromium/bin/**"]
  node_bundler = "esbuild"
  [functions.environment]
    CHROME_PATH = "/opt/build/repo/node_modules/chromium/lib/chromium/chrome-linux/chrome"

# Environment variables for Netlify
[build.environment]
  NODE_VERSION = "20"
  NETLIFY = "true"
  NODE_ENV = "production"


